### ISSUE TITLE
support task groupings

### ISSUE THREAD

**Issue by stephen** [samsarahq/taskrunner#5]
We may want shortcuts for common task sets, e.g. if we have `generate/constants`, `generate/types`,  `generate/somethingelse`, it'd be useful to have a `generate/all` task that does all of these.

I think we want to avoid allowing these groupings to have a declared dependence, since it promotes out of control dependency trees instead of selecting the minimum required dependency.

**Comment by berfarah** [comment]
Addressed by https://github.com/samsarahq/taskrunner/pull/9
